### ISSUE TITLE
Openstack validation fails with "Unknown" error

### ISSUE THREAD

**Issue by apophis90** [cloudfoundry-incubator/cf-openstack-validator#18]
Hi there,
I'm currently trying to deploy Cloud Foundry upon Devstack. The [CF docs](https://docs.cloudfoundry.org/deploying/cf-release/openstack/validate_openstack.html) recommend to do an automated verification of the Openstack/Devstack instance in use by means of the [cf-openstack-validator](https://github.com/cloudfoundry-incubator/cf-openstack-validator) project which in turn uses the Bosh Openstack CPI. The verification fails with the following error:

```
External CPI sending request: 
{
   "method":"create_stemcell",
   "arguments":[
      "/opt/stack/.cf-openstack-validator/stemcell/image",
      {
         "name":"bosh-openstack-kvm-ubuntu-trusty-go_agent",
         "version":"3468.1",
         "infrastructure":"openstack",
         "hypervisor":"kvm",
         "disk":3072,
         "disk_format":"qcow2",
         "container_format":"bare",
         "os_type":"linux",
         "os_distro":"ubuntu",
         "architecture":"x86_64",
         "auto_disk_config":true
      }
   ],
   "context":{
      "director_uuid":"validator",
      "request_id":"218563"
   }
}
with command: /opt/stack/.cf-openstack-validator/cpi

External CPI got response:
excon.error {:error=>#<Excon::Error::Found: Expected([200, 204, 300]) <=> Actual(302 Found)
excon.error.response
  :body          => "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>302 Found</title>\n</head><body>\n<h1>Found</h1>\n<p>The document has moved <a href=\"http://141.62.65.139/dashboard/\">here</a>.</p>\n<hr>\n<address>Apache/2.4.18 (Ubuntu) Server at 141.62.65.139 Port 80</address>\n</body></html>\n"
  :cookies       => [
  ]
  :headers       => {
    "Connection"     => "close"
    "Content-Length" => "294"
    "Content-Type"   => "text/html; charset=iso-8859-1"
    "Date"           => "Wed, 22 Nov 2017 15:24:09 GMT"
    "Location"       => "http://141.62.65.139/dashboard/"
    "Server"         => "Apache/2.4.18 (Ubuntu)"
  }
  :host          => "141.62.65.139"
  :local_address => "141.62.65.139"
  :local_port    => 53022
  :path          => "/"
  :port          => 80
  :reason_phrase => "Found"
  :remote_ip     => "141.62.65.139"
  :status        => 302
  :status_line   => "HTTP/1.1 302 Found\r\n"
>}

```  
So it looks like there're some problems dealing with the redirect to `/dashboard`.  
<br/>

My validator.yml:
```
---
openstack:
  auth_url: http://141.62.65.139/identity/v3 # Keystone V3 URL
  username: admin # String
  password: secret # String
  domain: default # String
  project: demo # String
  default_key_name: cf-validator # String
  default_security_groups: [default,cf-validator] # List of String
  boot_from_volume: false # Boolean
  config_drive: ~ # One of cdrom, disk, or nil
  connection_options: # all connection options that are supported by Excon
    ssl_verify_peer: false # Boolean
    # ca_cert: <replace-me> # Multiline yaml String containing certificate chain

validator:
  use_external_ip: true # Defines from where the Validator is executed. False means from inside your OpenStack.
  network_id: 641d1f8e-a83e-4ddb-a21f-c6b1b79c3154 # String UUID
  floating_ip: 172.24.4.2 # String IP
  static_ip: 172.24.4.2 # String IP. This IP is used to create a VM with a static IP.
  private_key_path: cf-validator.rsa_id # relative to validator.yml, or absolute path
  public_image_id: a3b4c230-1017-480a-92ca-3c604c5b0343 # String UUID
  ntp: [0.pool.ntp.org, 1.pool.ntp.org] # List of String
  mtu_size: 1500 # expected network MTU size in byte
  releases:
  - name: bosh-openstack-cpi
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=33
    sha1: 86b8eedcb0a6be3e821a5d0042916180706262be

cloud_config:
  vm_types: # See https://bosh.io/docs/cloud-config.html#vm-types
  - name: default # Don't change this name
    cloud_properties:
      instance_type: m1.small # String
      # availability_zone: <replace-me> # String
      # root_disk: {size: 20} # Integer, size in GiB. Used together with openstack.boot_from_volume.

extensions:
  paths: [] # paths pointing to a directory. Absolute or relative to this config file.
  config: {} # everything below 'config' is available in tests as `Validator::Api.configuration.extensions` inside your test code
```

<br/>
Versions in use:

  - Openstack-Validator: 2.4.0
  - Bosh CPI: v35 (latest release)
  -  Devstack Pike
