### ISSUE TITLE
Unable to start validator

### ISSUE THREAD

**Issue by StBurcher** [cloudfoundry-incubator/cf-openstack-validator#6]
Hi Guys,

I'm having a problem to start the validator.

```
$ ./validate --stemcell ../bosh-stemcell-3312.12-openstack-kvm-ubuntu-trusty-go_agent.tgz --config validator.yml
/home/ubuntu/cf-openstack-validator/lib/validator/cli.rb:18:in `require_relative': /home/ubuntu/cf-openstack-validator/lib/validator/cli/cf_openstack_validator.rb:160: syntax error, unexpected ',' (SyntaxError)
    def execute_command(env:, command:, log_path:, **options)
                             ^
/home/ubuntu/cf-openstack-validator/lib/validator/cli/cf_openstack_validator.rb:339: syntax error, unexpected keyword_end, expecting end-of-input
        from /home/ubuntu/cf-openstack-validator/lib/validator/cli.rb:18:in `<top (required)>'
        from ./validate:4:in `require_relative'
        from ./validate:4:in `<main>'
```

Using Ruby 2.0 on Ubuntu 16.04.

My Validator.yml looks like:

```
---
openstack:
  auth_url: https://10.10.0.10:35357/v3
  username: User # String
  password: PWD # String
  domain: Cloud Foundry # String
  project: Cloud Foundry # String

validator:
  network_id: 116355d4-c925-4c66-b49e-6ef8f64764cc # String UUID
  floating_ip: 192.168.0.16 # String IP
  static_ip: 10.0.0.99 # String IP. This IP is used to create a VM with a static IP.
  private_key_path: cf-validator.rsa_id # relative to validator.yml, no absolute path supported
  public_image_id: bd01892d-fddb-4416-b7f0-bdd3ad422d09 # String UUID
  ntp: [ntp.cloudlab.com] # List of String
  releases:
  - name: bosh-openstack-cpi
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/bosh-openstack-cpi-release?v=28
    sha1: beae72c7a105923ee74e7dfd6930e9aa75d86e05

cloud_config:
  vm_types: # See https://bosh.io/docs/cloud-config.html#vm-types
  - name: default # Don't change this name
    cloud_properties:
      instance_type: m1.medium # String
```
Any Ideas?
